sudo: required #is required to use docker service in travis

language: node_js #can be any language, just php for example
node_js:
  - "8.9.3"

services:
  - docker 

env:
  global:
    - IMAGE_NAME=$DOCKER_USERNAME/timetracker

before_script:
  - if [ $TRAVIS_BRANCH == "master" ]; then
        export TAG=latest
    else
        export TAG=$TRAVIS_BRANCH-DEV
    fi

  - echo $TAG
  
script:
  - npm test

after_success:
  - docker --version  # document the version travis is using
  - docker build -t $IMAGE_NAME:$TAG .

  #- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" # hidden in travis-ci.org settings of timetracker project
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin  # hidden in travis-ci.org settings of timetracker project
  - docker images
  
  - docker tag $IMAGE_NAME:$TAG $REPO:$TAG
  - docker tag $IMAGE_NAME:$TAG $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $IMAGE_NAME
