version: "3"
services:
  node-app:
    container_name: timetracker
    restart: always
    build: .
    image: nobio/timetracker
    environment:
      #- MONGO_URL=mongodb://mongo:27017/timetracker
      - MONGO_URL=mongodb://nobio:1gR7hW2cPhtkRlv2@ds061928.mlab.com:61928/timetrack
      #- MONGO_URL=mongodb://nobio:1gR7hW2cPhtkRlv2@ds061928.mlab.com:61928/timetrack with options {"useMongoClient":true,"reconnectTries":1000,"reconnectInterval":500,"poolSize":5,"keepAlive":120,"bufferMaxEntries":-1}
    volumes:
      # in-host:in-container
      - ./dump:/usr/src/app/dump
    ports:
      - "30030:30000"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    volumes:
      # in-host:in-container
      - ./data:/data/db
    ports:
      - "27017:27017"